apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.5.0
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: ibm-common-service-operator
    app.kubernetes.io/managed-by: ibm-common-service-operator
    app.kubernetes.io/name: ibm-common-service-operator
  name: commonservices.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: CommonService
    listKind: CommonServiceList
    plural: commonservices
    singular: commonservice
  scope: Namespaced
  versions:
  - name: v3
    schema:
      openAPIV3Schema:
        description: CommonService is the Schema for the commonservices API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CommonServiceSpec defines the desired state of CommonService
            properties:
              BYOCACertificate:
                type: boolean
              catalogName:
                type: string
              catalogNamespace:
                type: string
              defaultAdminUser:
                type: string
              features:
                description: Features defines the configurations of Cloud Pak Services
                properties:
                  apiCatalog:
                    description: APICatalog defines the configuration of APICatalog
                    properties:
                      storageClass:
                        type: string
                    type: object
                  bedrockshim:
                    description: Bedrockshim defines the configuration of Bedrockshim
                    properties:
                      crossplaneProviderRemoval:
                        type: boolean
                      enabled:
                        type: boolean
                    type: object
                type: object
              fipsEnabled:
                type: boolean
              installPlanApproval:
                description: Approval is the user approval policy for an InstallPlan.
                  It must be one of "Automatic" or "Manual".
                type: string
              license:
                description: LicenseList defines the license specification in CSV
                properties:
                  accept:
                    description: 'Accepting the license - URL: https://ibm.biz/integration-licenses'
                    type: boolean
                  key:
                    description: The license key for this deployment.
                    type: string
                  license:
                    description: The license being accepted where the component has
                      multiple.
                    type: string
                  use:
                    description: The type of license being accepted.
                    type: string
                type: object
              manualManagement:
                type: boolean
              operatorNamespace:
                type: string
              profileController:
                type: string
              routeHost:
                type: string
              services:
                items:
                  properties:
                    managementStrategy:
                      type: string
                    name:
                      type: string
                    spec:
                      additionalProperties:
                        type: object
                      type: object
                  required:
                  - name
                  - spec
                  type: object
                type: array
              servicesNamespace:
                type: string
              size:
                type: string
              storageClass:
                type: string
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: CommonServiceStatus defines the observed state of CommonService
            properties:
              bedrockOperators:
                items:
                  description: BedrockOperator maintains a list of bedrock operators
                  properties:
                    installPlanName:
                      type: string
                    name:
                      type: string
                    operatorStatus:
                      type: string
                    subscriptionStatus:
                      type: string
                    troubleshooting:
                      type: string
                    version:
                      type: string
                  type: object
                type: array
              configStatus:
                properties:
                  catalogName:
                    type: string
                  catalogNamespace:
                    type: string
                  configurable:
                    type: boolean
                  operatorDeployed:
                    type: boolean
                  operatorNamespace:
                    type: string
                  servicesDeployed:
                    type: boolean
                  servicesNamespace:
                    type: string
                  topologyConfigurableCRs:
                    items:
                      properties:
                        apiVersion:
                          type: string
                        kind:
                          type: string
                        namespace:
                          type: string
                        objectName:
                          type: string
                      type: object
                    type: array
                required:
                - configurable
                - operatorDeployed
                - servicesDeployed
                type: object
              overallStatus:
                type: string
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
