imEnabled: "true" #should this be a global value? Is there a better way to determine this?

#stand-in global values for testing
global:
  operatorNamespace: "cs-op"
  instanceNamespace: "cs-serv"
  tetheredNamespaces: [""]
  installConfigImagePullPrefix: ""  # Optional, CPD requested: Override image pull prefix for installation config
  imagePullPrefix: icr.io
  imagePullSecret: ibm-entitlement-key

cpfs:
  imageRegistryNamespaceOperand: cpopen/cpfs