apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: "ibm-common-service-operator"
    app.kubernetes.io/managed-by: "ibm-common-service-operator"
    app.kubernetes.io/name: "ibm-common-service-operator"
  name: ibm-common-service-operator
  