apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: system/serving-cert
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-operator-ibm-com-v3-commonservice
  failurePolicy: Fail
  name: vcommonservice.kb.io
  rules:
  - apiGroups:
    - operator.ibm.com
    apiVersions:
    - v3
    operations:
    - CREATE
    - UPDATE
    resources:
    - commonservices
  sideEffects: None
